application:
  name: Travels History
spring:
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    database-plataform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console